services:
  - type: web
    name: nyaysetu
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false
